services:
  - type: web
    plan: free
    name: DxStreamerBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m Dxbots 
    repo: https://github.com/DX-MODS/DxStreamerBot.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: BIN_CHANNEL
        sync: false
      - key: UPDATES_CHANNEL
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FQDN
        sync: false
    autoDeploy: false
